apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zm0ulep83-nodejs
  janus-idp.io/tekton: zm0ulep83-nodejs
  backstage.io/kubernetes-id: zm0ulep83-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zm0ulep83-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
