apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zm0ulep83-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zm0ulep83-nodejs 
  name: zm0ulep83-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zm0ulep83-nodejs 
